In [1]:
import numpy as np

from iteration.vector import power_iteration, get_eigenvalue

In [2]:
A = np.array([
    [1., 0.],
    [2., 2.]
])

In [3]:
eigenvector1 = A @ power_iteration(A, steps=100)
eigenvalue1 = get_eigenvalue(A, eigenvector1)
eigenvector1, eigenvalue1, A @ eigenvector1

(array([2.6169483e-31, 2.0000000e+00]),
 2.0,
 array([2.6169483e-31, 4.0000000e+00]))

In [4]:
eigenvector2 = power_iteration(A, gamma = 2., steps=100)
eigenvalue2 = get_eigenvalue(A, eigenvector2)
eigenvector2, eigenvalue2, A @ eigenvector2

(array([ 0.4472136 , -0.89442719]), 1.0, array([ 0.4472136 , -0.89442719]))