In [1]:
import numpy as np

from iteration.vector import gauss_seidel_iteration, jacobi_iteration, steepest_descent

In [2]:
A = np.array([
        [3.,0.,1.,0.],
        [0.,1.,0.,1.],
        [1.,0.,1.,0.],
        [0.,0.,2.,1.],      
])
b = np.array([[1.],[2.],[4.],[2.]])

In [3]:
steepest_descent(A,b)

array([[-1.5],
       [11. ],
       [ 5.5],
       [-9. ]])

In [4]:
gauss_seidel_iteration(A,b)

array([[-1.5],
       [11. ],
       [ 5.5],
       [-9. ]])

In [5]:
jacobi_iteration(A,b)

array([[-1.5],
       [11. ],
       [ 5.5],
       [-9. ]])