In [6]:
import numpy as np

from iteration.vector import gauss_seidel_iteration, jacobi_iteration, steepest_descent

In [7]:
A = np.array([
        [3.,0.,1.,0.],
        [0.,1.,0.,1.],
        [1.,0.,1.,0.],
        [0.,0.,2.,1.],      
])
b = np.array([[1.],[2.],[4.],[2.]])

In [8]:
steepest_descent(A,b)

array([[-1.5],
       [11. ],
       [ 5.5],
       [-9. ]])

In [9]:
gauss_seidel_iteration(A,b)

array([[-1.5],
       [11. ],
       [ 5.5],
       [-9. ]])

In [10]:
jacobi_iteration(A,b)

array([[-1.5],
       [11. ],
       [ 5.5],
       [-9. ]])